### PR TITLE
chore: manually track page view

### PR DESCRIPTION
**Pull request by Barbapapazes**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 📰 Content (a new article or a change in the content folder)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Manually track page view to avoid to many request when use URL as state of the application.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by pi0** [comment]
I think this should have been an option in upstream module.

**Comment by Barbapapazes** [comment]
> I think this should have been an option in upstream module.

Yes but no commit since 2 years. So doing a proposal for this will have no end actually.

https://github.com/plausible/plausible-tracker/issues/61

**Comment by pi0** [comment]
Then we might consider replacing it. /cc @Atinux

**Comment by Atinux** [comment]
I think we should update the module instead.

Not sure about this issue though of the query parameters as it can be useful to track too since it is a different state.

**Comment by pi0** [comment]
If we update and maintain module i think perhaps we can introduce a new page meta to disable tracking query params when it is not wanted it seems a valid requirement IMO for pages that use query as state holder and only need tracking for main URLs.

**Comment by Barbapapazes** [comment]
> I think we should update the module instead.
> 
> Not sure about this issue though of the query parameters as it can be useful to track too since it is a different state.

The issue of tracking every state of the URL is that for an query input, every type will be pushed to plausible (could cause a lot of input so increase the price of the service?). I prefer to manually send some params over time, like https://github.com/nuxt/nuxt.com/blob/main/app.vue#L37

**Comment by Atinux** [comment]
Since this

**Comment by Barbapapazes** [comment]
> Not sure about this issue though of the query parameters as it can be useful to track too since it is a different state.

Plausible will remove query parameters so this will only send page event. (see https://plausible.io/docs/custom-query-params)

 > If we update and maintain module i think perhaps we can introduce a new page meta to disable tracking query params when it is not wanted it seems a valid requirement IMO for pages that use query as state holder and only need tracking for main URLs.

I made a fork: https://github.com/barbapapazes/plausible-tracker. It will be release within the next version of Nuxt Plausible module. Maybe we could try to make something smarter.

**Pull request merged**
