### PR TITLE
ci: create update packages

### PR DESCRIPTION
**Pull request by Barbapapazes**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme, or JSdoc annotations)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [x] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This PR will allow use to easily track packages (added or removed) from the UnJS organization and to be sure that website is in sync.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Barbapapazes** [comment]
Before being able to merge it, I need you @pi0 to activate "Allow GitHub Actions to create or approve Pull Request" in the Settings > Actions tab! Thanks!

**Comment by pi0** [comment]
Should be already enabled:

image

**Comment by Barbapapazes** [comment]
> Should be already enabled:
> 
> image
> 

Nice, thanks you! (I can't see this setting with my permission!)

**Comment by pi0** [comment]
You should have admin perm now 💯

**Pull request merged**
