### PR TITLE
fix: build url from github relative path (fixed #4)

### LINKED ISSUE #4: Assets in project markdown resolved with wrong base URL
Hey! Image assets of project markdown are resolved wrongly.

# Reproduction

1. Go to https://unjs.io/webpackbar
2. See the logo is resolved as "https://unjs.io/assets/logo.svg", in original repo as "https://github.com/unjs/webpackbar/raw/main/assets/logo.svg"

### PR DESCRIPTION
**Pull request by serkodev**
Fixed #4

- Add `https://github.com/{user}/{repo}/raw/main/{path}` to `` `src`
- Add `https://github.com/{user}/{repo}/blob/main/{path}` to `<a>` `href`

#### Dependencies
- `ufo` to parse and generate URL
- `cheerio` to modify `README` HTML

### CODE REVIEW

**Comment by serkodev** [comment]
### Result preview
The image links are clickable to link to the original GitHub file.

result

**Comment by manniL** [comment]
First of all: Thanks for you contribution and good job! 👏 

I was thinking - maybe the contribution would even fit better at the root - in the `ghMarkdown` function of `ungh` - https://github.com/unjs/ungh/blob/main/server/utils/github.ts#L39

That way the client is kept lean and everybody using the endpoint(s) can benefits 😋 

Happy to hear input from @pi0 too on that!

**Comment by serkodev** [comment]
Sounds good. 🤩

By the way I think modify the original content **by default** is not a good idea. To add this to `ungh`, it may be better to provide optional setting (something like `/markdown?ghhost=1`). What do you think?

FYI, there is a library called [marky-markdown](https://github.com/npm/marky-markdown) by [npm](https://github.com/npm) which can convert markdown file to HTML with [adding hosts](https://github.com/npm/marky-markdown/blob/master/lib/plugin/github.js).

**Comment by serkodev** [comment]
Just forgot to say, I also tried using [happy-dom](https://github.com/capricorn86/happy-dom) and [jsdom](https://github.com/jsdom/jsdom) to parse and generate HTML but it seems has some bug on Nuxt.

Maybe generate it from server side can using these library to improve performance. 😁

**Comment by manniL** [comment]
> By the way I think modify the original content **by default** is not a good idea. To add this to `ungh`, it may be better to provide optional setting (something like `/markdown?ghhost=1` / `/readme?ghhost=1`). What do you think?

I wonder why this should be optional though 🤔 
The only reason I can come up is because is "different" from typical API output.

**Comment by serkodev** [comment]
> I wonder why this should be optional though 🤔

Are there situations where developers might want to point the URL to a branch other than `main` (like `master`) or to another domain such as `raw.githubusercontent.com`?
So I think it is more suitable to keep original by default and let developers to customize the path.

**Comment by serkodev** [comment]
@manniL @pi0 
just saw @Atinux commited https://github.com/unjs/website/commit/28f8135461f3f97912f5504faa8bae5c1f5c7a6d
so does this PR still need to be discussed?

**Comment by manniL** [comment]
I would still keep it out! Let's see what Atinux and pi0 say ☺️

**Comment by manniL** [comment]
I personally am still not happy with adding the whole cheerio lib to the frontend. If it doesn't make sense moving it to ungh, we could move it to a server endpoint instead that acts as a proxy and applies transformations? This way, the frontend has less JS ☺️

**Comment by pi0** [comment]
Thanks for the PR. As hotfix landed, site should be ok but we need to fix it in upstream ungh to resolve local asset URLs when rendering markup.

**Pull request closed without merging**
