### PR TITLE
chore: refactor components

### PR DESCRIPTION
**Pull request by NozomuIkuta**
I just refactored some parts of the code base:

- Unify the order of blocks in SFC files (i.e. `script` 👉 `template` 👉  `style`)
- Rename files in `components` directory as Pascal Case, for them to be aligned with sample codes in Nuxt official site
- Rename `github-logo.vue` (i.e. `<GithubLogo />`) as `GitHubLogo.vue` (i.e. `<GitHubLogo />`) for the service name to be correct
- Use `<script setup>` and its features as much as possible
- Clean up redundant spaces

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for PR dear @NozomuIkuta ❤️ Can you please rebase your branch?

**Comment by NozomuIkuta** [comment]
@pi0 

Thank you for the notice!
I've resolved the conflicts. 🙋‍♂️

**Comment by NozomuIkuta** [comment]
@manniL 

Merged `main` branch and resolved conflicts 🙋‍♂️

**Review by manniL — APPROVED** [review]

**Comment by NozomuIkuta** [comment]
@pi0 

I'm thinking of merging my PRs once they are approved by unjs members.

Please let me know and stop me as you need.

Now I will merge this PR and so on.

**Pull request merged**
